### ISSUE TITLE
Not able to run 

### ISSUE THREAD

**Issue by cybertricks** [flipkart-incubator/watchdog#4]
ubuntu@ip-172-31-45-76:~/watchdog$ sudo python run.py -h
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from fillInventory import fill_Inventory
  File "/home/ubuntu/watchdog/fillInventory.py", line 2, in <module>
    from mongo_connection import mongo_client
  File "/home/ubuntu/watchdog/mongo_connection.py", line 1, in <module>
    from pymongo import MongoClient
ImportError: No module named pymongo

**Comment by cybertricks** [comment]
I have run the below command 
sudo python -m pip install pymongo

it is fixed and now i  am getting 

ubuntu@ip-172-31-45-76:~/watchdog$ sudo python run.py
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    from start_scans import start_scan
  File "/home/ubuntu/watchdog/start_scans.py", line 7, in <module>
    from findTechnology import technologyScan
  File "/home/ubuntu/watchdog/findTechnology.py", line 1, in <module>
    from wappalyzer import Wappalyzer
ImportError: No module named wappalyzer

**Comment by prajal** [comment]
This seems like pyv8 issue.. Could you try these steps 
$ export LC_ALL=C
$ cd /tmp
$ pip install -e git://github.com/brokenseal/PyV8-OS-X#egg=pyv8
$ git clone https://github.com/emmetio/pyv8-binaries.git
$ unzip pyv8-binaries/pyv8-linux64.zip (or unzip appropriate zip file based on kernal version)
$ mv *PyV8* src/pyv8/pyv8/.

**Comment by cybertricks** [comment]
Hi Team

I have done that.

**Comment by prajal** [comment]
Could you share what result you get importing PyV8 in python 

praj:~ prajal.kulkarni$ python
Python 2.7.10 (default, Oct  6 2017, 22:29:07)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyV8

**Comment by cybertricks** [comment]
ubuntu@ip-172-31-45-76:~$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by prajal** [comment]
seems like PyV8 was previously installed on the system could be a compatibility issue. You could try a fresh installation

**Comment by cybertricks** [comment]
It was some compatibility issue,it is fixed with the new installation.
Thank you for the support.

**Comment by prajal** [comment]
Perfect! Do give us your feedback on completing the first run!

**Comment by fferraro87** [comment]
@cybertricks @prajal 
i've same error, so how can i fix? How can i reinstall pyV8?

Thanks

**Comment by fferraro87** [comment]
if i do python and i try to import PyV8 i've that output : 
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named PyV8`
